#!/usr/bin/env python3
"""Generate seed.sql from data/catalog_clean.csv + snapshot content.

Seeds: categories (8 live + 8 dormant), brands, models, variants, prices, faqs.
Idempotent-ish: written for a fresh schema (no ON CONFLICT churn needed).
Run the output in the Supabase SQL editor after schema.sql.
"""
import csv, re, pathlib, collections

ROOT = pathlib.Path(__file__).resolve().parent.parent
rows = list(csv.DictReader(open(ROOT / "data" / "catalog_clean.csv")))

LIVE = ["Cell Phone","Tablet","Smartwatch","Game Console","GoPro","VR","Headphones","iPod"]
DORMANT = ["Macbook","Laptop","iMac","Mac Mini","Mac Studio","Mac Pro","Apple TV","Drone"]
CAT_SLUG = {"Cell Phone":"cell-phone","Tablet":"tablet","Smartwatch":"smartwatch","Game Console":"game-console",
            "GoPro":"gopro","VR":"vr","Headphones":"headphones","iPod":"ipod","Macbook":"macbook","Laptop":"laptop",
            "iMac":"imac","Mac Mini":"mac-mini","Mac Studio":"mac-studio","Mac Pro":"mac-pro","Apple TV":"apple-tv",
            "Drone":"drone"}
CAT_DISPLAY = {"Cell Phone":"Cell Phones","Tablet":"Tablets","Smartwatch":"Smartwatches","Game Console":"Game Consoles",
               "GoPro":"GoPro","VR":"VR","Headphones":"Headphones","iPod":"iPods","Macbook":"MacBooks","Laptop":"Laptops",
               "iMac":"iMacs","Mac Mini":"Mac Minis","Mac Studio":"Mac Studios","Mac Pro":"Mac Pros",
               "Apple TV":"Apple TV","Drone":"Drones"}
CAT_IMGDIR = {"Cell Phone":"cell-phones","Tablet":"tablets","Smartwatch":"smartwatches","Game Console":"game-consoles",
              "GoPro":"gopros","VR":"vrs","Headphones":"headphones","iPod":"ipods","Macbook":"macbooks","Laptop":"laptops",
              "iMac":"imacs","Mac Mini":"mac-minis","Mac Studio":"mac-studios","Mac Pro":"mac-pros",
              "Apple TV":"apple-tvs","Drone":"drones"}
CAT_LABELS = {"Smartwatch":("Which case?","What size?"),"Game Console":("Which edition?","How much storage?"),
              "GoPro":("Which edition?","Which bundle?"),"Tablet":("Which connectivity?","How much storage?"),
              "VR":("Which edition?","How much storage?"),"Headphones":("Which edition?","Which color?"),
              "iPod":("Which generation?","How much storage?")}

SLUG_OVERRIDES = {  # live-site slugs frozen in Google's index — keep in sync with generator
    "Series 7 GPS + Cellular": "series-7-gps-cellular",
    "Series 8 GPS + Cellular": "series-8-gps-cellular",
    "Series 9 GPS + Cellular": "series-9-gps-cellular",
    "Series 10 GPS + Cellular": "series-10-gps-cellular",
    "iPad Pro 11 M5 Nano-texture Glass (2025)": "ipad-pro-11-m5-nanominustexture-glass-2025",
    "iPad Pro 13 M5 Nano-texture Glass (2025)": "ipad-pro-13-m5-nanominustexture-glass-2025",
}
def slug(s):
    if s in SLUG_OVERRIDES: return SLUG_OVERRIDES[s]
    s = s.lower().replace("&","and").replace("+","-plus")
    return re.sub(r"[^a-z0-9]+","-",s).strip("-")

def q(s):
    return "'" + s.replace("'","''") + "'"

out = ["-- Generated by supabase/generate_seed.py — run after schema.sql", "begin;"]

# categories
for i, cat in enumerate(LIVE + DORMANT):
    q1, q2 = CAT_LABELS.get(cat, ("Which carrier?","How much storage?"))
    out.append(f"insert into categories (name, slug, display_name, image_dir, q1_label, q2_label, sort, enabled) "
               f"values ({q(cat)}, {q(CAT_SLUG[cat])}, {q(CAT_DISPLAY[cat])}, {q(CAT_IMGDIR[cat])}, {q(q1)}, {q(q2)}, {i}, {str(cat in LIVE).lower()});")

# brands
brand_names = sorted(set(r["Brand"] for r in rows))
for b in brand_names:
    out.append(f"insert into brands (name, slug) values ({q(b)}, {q(slug(b))});")

# models (min sort across rows; enabled if any enabled row)
models = {}
for r in rows:
    k = (r["Category"], r["Brand"], r["Device"])
    m = models.setdefault(k, {"sort": 10**9, "enabled": False})
    m["sort"] = min(m["sort"], int(r["Sort Order"] or 10**9))
    m["enabled"] = m["enabled"] or r["Enabled"] == "true"
for (cat, brand, dev), m in models.items():
    img = f"https://s3.amazonaws.com/fliptech-assets/images/devices/{CAT_IMGDIR[cat]}/{slug(brand)}/{slug(dev)}.webp"
    out.append(
        "insert into models (category_id, brand_id, name, slug, image_url, sort, enabled) values ("
        f"(select id from categories where name={q(cat)}), (select id from brands where name={q(brand)}), "
        f"{q(dev)}, {q(slug(dev))}, {q(img)}, {m['sort']}, {str(m['enabled']).lower()});")

# variants + prices
variants = collections.OrderedDict()
for r in rows:
    vk = (r["Category"], r["Brand"], r["Device"], r["Carrier"] or "-", r["Storage Capacity"] or "-")
    variants.setdefault(vk, []).append(r)
for (cat, brand, dev, carrier, storage), prs in variants.items():
    out.append(
        "insert into variants (model_id, carrier, storage) values ("
        f"(select m.id from models m join categories c on c.id=m.category_id join brands b on b.id=m.brand_id "
        f"where c.name={q(cat)} and b.name={q(brand)} and m.name={q(dev)}), {q(carrier)}, {q(storage)});")
    vals = []
    for r in prs:
        price = float(r["Price"] or 0)
        vals.append(f"(currval('variants_id_seq'), {q(r['Condition'])}, {price}, {r['Enabled']})")
    out.append("insert into prices (variant_id, condition, price, enabled) values " + ", ".join(vals) + ";")

# faqs (live content, cleaned of insurance/PayPal per Sep 2026 decisions)
faqs = [
    ("How long is my offer good for?",
     "The offer is good for 14 days beginning the day the order is submitted to us. If an item arrives after the 14-day mark, the current offer for the device will be given."),
    ("How do I ship an item?",
     "After checkout we email you a free prepaid USPS shipping label. Pack your device in any sturdy box and drop it at any Post Office or USPS pickup location."),
    ("How do I track my package?",
     "Use the Track Order page with your order number and email — you can follow your trade-in from shipment through payment."),
    ("How are the electronics evaluated?",
     "Devices are evaluated with diagnostic software that verifies the model and tests all functionality, then manually inspected for physical condition, authenticity, water damage, and account locks. If your self-assessment was accurate, payment is sent in the method you selected. If not, we send a revised offer you can accept — or we ship your item back free."),
    ("What do I need to send in to get the quoted offer amount?",
     "Just the device itself unless noted otherwise. Include chargers or accessories only when the quote page asks for them."),
    ("What if I'm not sure about the condition of my product?",
     "Pick your best guess — every device is checked on arrival. If our grade differs you'll get a new offer to accept, or we return your device free."),
    ("How and when will I get paid?",
     "Within 1 business day of your device arriving — by PayPal, Zelle, Venmo, or check. Locals can choose cash on the spot at our Brea store."),
    ("Is there a limit on the number of items I can sell?",
     "No — sell one device or a whole drawer full. Bulk trade-ins welcome."),
    ("What if I do not agree with the evaluation of my phone?",
     "You can reject the revised offer and we'll ship your device back to you at no cost."),
    ("My package weighs more than the weight shown on the shipping label. What should I do?",
     "That's okay — USPS bills us for any difference in weight, not you. Just ship it."),
]
for i,(question, answer) in enumerate(faqs):
    out.append(f"insert into faqs (question, answer, sort) values ({q(question)}, {q(answer)}, {i});")

# core settings
out.append("""insert into site_settings (key, value) values
('contact', '{"phone":"657-286-8274","email":"support@ocbuyback.com","address1":"1203 W Imperial Hwy","address2":"STE 103","city":"Brea","state":"CA","zip":"92821"}'),
('store_hours', '{"mon":"10:00-18:00","tue":"10:00-18:00","wed":"10:00-18:00","thu":"10:00-18:00","fri":"10:00-18:00","sat":null,"sun":null}'),
('quote', '{"price_lock_days":14,"payment_methods":["paypal","check","zelle","venmo","cash"]}');""")

out.append("commit;")
path = ROOT / "supabase" / "seed.sql"
path.write_text("\n".join(out) + "\n")
n_models = len(models); n_vars = len(variants); n_prices = len(rows)
print(f"seed.sql written: {len(LIVE+DORMANT)} categories, {len(brand_names)} brands, "
      f"{n_models} models, {n_vars} variants, {n_prices} prices, {len(faqs)} faqs")
