begin;
update models set weight_oz = 8 where name = '10 Pro' and enabled;
update models set weight_oz = 7 where name = '11' and enabled;
update models set weight_oz = 7 where name = '12' and enabled;
update models set weight_oz = 7 where name = '12R' and enabled;
update models set weight_oz = 7 where name = '13' and enabled;
update models set weight_oz = 7 where name = '13R' and enabled;
update models set weight_oz = 7 where name = '15' and enabled;
update models set weight_oz = 7 where name = '15R' and enabled;
update models set weight_oz = 8 where name = '7 Pro' and enabled;
update models set weight_oz = 7 where name = '7T' and enabled;
update models set weight_oz = 7 where name = '8 5G' and enabled;
update models set weight_oz = 8 where name = '8 Pro' and enabled;
update models set weight_oz = 7 where name = '9' and enabled;
update models set weight_oz = 8 where name = '9 Pro' and enabled;
update models set weight_oz = 9 where name = 'Galaxy Fold' and enabled;
update models set weight_oz = 8 where name = 'Galaxy Note 10' and enabled;
update models set weight_oz = 8 where name = 'Galaxy Note 10+ 4G' and enabled;
update models set weight_oz = 8 where name = 'Galaxy Note 20' and enabled;
update models set weight_oz = 8 where name = 'Galaxy Note 20 5G' and enabled;
update models set weight_oz = 9 where name = 'Galaxy Note 20 Ultra' and enabled;
update models set weight_oz = 8 where name = 'Galaxy Note 8' and enabled;
update models set weight_oz = 8 where name = 'Galaxy Note 9' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S10 4G' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S10 5G' and enabled;
update models set weight_oz = 8 where name = 'Galaxy S10 Plus' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S10e' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S20' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S20 FE' and enabled;
update models set weight_oz = 8 where name = 'Galaxy S20 Plus' and enabled;
update models set weight_oz = 9 where name = 'Galaxy S20 Ultra' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S21' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S21 FE' and enabled;
update models set weight_oz = 8 where name = 'Galaxy S21 Plus' and enabled;
update models set weight_oz = 9 where name = 'Galaxy S21 Ultra' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S22' and enabled;
update models set weight_oz = 8 where name = 'Galaxy S22 Plus' and enabled;
update models set weight_oz = 9 where name = 'Galaxy S22 Ultra' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S23' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S23 FE' and enabled;
update models set weight_oz = 8 where name = 'Galaxy S23 Plus' and enabled;
update models set weight_oz = 9 where name = 'Galaxy S23 Ultra' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S24' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S24 Fe' and enabled;
update models set weight_oz = 8 where name = 'Galaxy S24 Plus' and enabled;
update models set weight_oz = 9 where name = 'Galaxy S24 Ultra' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S25' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S25 Edge' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S25 FE' and enabled;
update models set weight_oz = 8 where name = 'Galaxy S25 Plus' and enabled;
update models set weight_oz = 9 where name = 'Galaxy S25 Ultra' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S26' and enabled;
update models set weight_oz = 8 where name = 'Galaxy S26 Plus' and enabled;
update models set weight_oz = 9 where name = 'Galaxy S26 Ultra' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S7' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S7 Edge' and enabled;
update models set weight_oz = 7 where name = 'Galaxy S9' and enabled;
update models set weight_oz = 8 where name = 'Galaxy S9 Plus' and enabled;
update models set weight_oz = 7 where name = 'Galaxy Z Flip 4G' and enabled;
update models set weight_oz = 7 where name = 'Galaxy Z Flip 5G' and enabled;
update models set weight_oz = 7 where name = 'Galaxy Z Flip3' and enabled;
update models set weight_oz = 7 where name = 'Galaxy Z Flip4' and enabled;
update models set weight_oz = 7 where name = 'Galaxy Z Flip5' and enabled;
update models set weight_oz = 7 where name = 'Galaxy Z Flip6' and enabled;
update models set weight_oz = 7 where name = 'Galaxy Z Flip7' and enabled;
update models set weight_oz = 7 where name = 'Galaxy Z Flip7 FE' and enabled;
update models set weight_oz = 9 where name = 'Galaxy Z Fold2' and enabled;
update models set weight_oz = 9 where name = 'Galaxy Z Fold3' and enabled;
update models set weight_oz = 9 where name = 'Galaxy Z Fold4' and enabled;
update models set weight_oz = 9 where name = 'Galaxy Z Fold5' and enabled;
update models set weight_oz = 9 where name = 'Galaxy Z Fold6' and enabled;
update models set weight_oz = 9 where name = 'Galaxy Z Fold7' and enabled;
update models set weight_oz = 7 where name = 'iPhone 11' and enabled;
update models set weight_oz = 8 where name = 'iPhone 11 Pro' and enabled;
update models set weight_oz = 9 where name = 'iPhone 11 Pro Max' and enabled;
update models set weight_oz = 7 where name = 'iPhone 12' and enabled;
update models set weight_oz = 5 where name = 'iPhone 12 Mini' and enabled;
update models set weight_oz = 8 where name = 'iPhone 12 Pro' and enabled;
update models set weight_oz = 9 where name = 'iPhone 12 Pro Max' and enabled;
update models set weight_oz = 7 where name = 'iPhone 13' and enabled;
update models set weight_oz = 5 where name = 'iPhone 13 Mini' and enabled;
update models set weight_oz = 8 where name = 'iPhone 13 Pro' and enabled;
update models set weight_oz = 9 where name = 'iPhone 13 Pro Max' and enabled;
update models set weight_oz = 7 where name = 'iPhone 14' and enabled;
update models set weight_oz = 8 where name = 'iPhone 14 Plus' and enabled;
update models set weight_oz = 8 where name = 'iPhone 14 Pro' and enabled;
update models set weight_oz = 9 where name = 'iPhone 14 Pro Max' and enabled;
update models set weight_oz = 7 where name = 'iPhone 15' and enabled;
update models set weight_oz = 8 where name = 'iPhone 15 Plus' and enabled;
update models set weight_oz = 8 where name = 'iPhone 15 Pro' and enabled;
update models set weight_oz = 9 where name = 'iPhone 15 Pro Max' and enabled;
update models set weight_oz = 7 where name = 'iPhone 16' and enabled;
update models set weight_oz = 8 where name = 'iPhone 16 Plus' and enabled;
update models set weight_oz = 8 where name = 'iPhone 16 Pro' and enabled;
update models set weight_oz = 9 where name = 'iPhone 16 Pro Max' and enabled;
update models set weight_oz = 6 where name = 'iPhone 16e' and enabled;
update models set weight_oz = 7 where name = 'iPhone 17' and enabled;
update models set weight_oz = 8 where name = 'iPhone 17 Pro' and enabled;
update models set weight_oz = 9 where name = 'iPhone 17 Pro Max' and enabled;
update models set weight_oz = 6 where name = 'iPhone 17e' and enabled;
update models set weight_oz = 7 where name = 'iPhone 8' and enabled;
update models set weight_oz = 8 where name = 'iPhone 8 Plus' and enabled;
update models set weight_oz = 6 where name = 'iPhone Air' and enabled;
update models set weight_oz = 6 where name = 'iPhone SE 2nd Gen (2020)' and enabled;
update models set weight_oz = 6 where name = 'iPhone SE 3rd Gen (2022)' and enabled;
update models set weight_oz = 7 where name = 'iPhone X' and enabled;
update models set weight_oz = 7 where name = 'iPhone XR' and enabled;
update models set weight_oz = 7 where name = 'iPhone XS' and enabled;
update models set weight_oz = 7 where name = 'iPhone XS Max' and enabled;
update models set weight_oz = 7 where name = 'Open' and enabled;
update models set weight_oz = 7 where name = 'Pixel 10' and enabled;
update models set weight_oz = 8 where name = 'Pixel 10 Pro' and enabled;
update models set weight_oz = 10 where name = 'Pixel 10 Pro Fold' and enabled;
update models set weight_oz = 9 where name = 'Pixel 10 Pro XL' and enabled;
update models set weight_oz = 7 where name = 'Pixel 10a' and enabled;
update models set weight_oz = 7 where name = 'Pixel 4a' and enabled;
update models set weight_oz = 7 where name = 'Pixel 6' and enabled;
update models set weight_oz = 8 where name = 'Pixel 6 Pro' and enabled;
update models set weight_oz = 7 where name = 'Pixel 6a' and enabled;
update models set weight_oz = 7 where name = 'Pixel 7' and enabled;
update models set weight_oz = 8 where name = 'Pixel 7 Pro' and enabled;
update models set weight_oz = 7 where name = 'Pixel 7a' and enabled;
update models set weight_oz = 7 where name = 'Pixel 8' and enabled;
update models set weight_oz = 8 where name = 'Pixel 8 Pro' and enabled;
update models set weight_oz = 7 where name = 'Pixel 8a' and enabled;
update models set weight_oz = 7 where name = 'Pixel 9' and enabled;
update models set weight_oz = 8 where name = 'Pixel 9 Pro' and enabled;
update models set weight_oz = 10 where name = 'Pixel 9 Pro Fold' and enabled;
update models set weight_oz = 9 where name = 'Pixel 9 Pro XL' and enabled;
update models set weight_oz = 7 where name = 'Pixel 9a' and enabled;
update models set weight_oz = 10 where name = 'Pixel Fold' and enabled;
update models set weight_oz = 19 where name = 'playstation portal' and enabled;
update models set weight_oz = 32 where name = 'Playstation VR Headset' and enabled;
update models set weight_oz = 53 where name = 'ps1' and enabled;
update models set weight_oz = 78 where name = 'ps2' and enabled;
update models set weight_oz = 32 where name = 'ps2 slim' and enabled;
update models set weight_oz = 176 where name = 'ps3' and enabled;
update models set weight_oz = 113 where name = 'ps3 slim' and enabled;
update models set weight_oz = 74 where name = 'ps3 super slim' and enabled;
update models set weight_oz = 99 where name = 'ps4' and enabled;
update models set weight_oz = 117 where name = 'ps4 pro' and enabled;
update models set weight_oz = 74 where name = 'ps4 slim' and enabled;
update models set weight_oz = 159 where name = 'ps5' and enabled;
update models set weight_oz = 138 where name = 'ps5 digital edition' and enabled;
update models set weight_oz = 110 where name = 'ps5 pro' and enabled;
update models set weight_oz = 113 where name = 'ps5 slim' and enabled;
update models set weight_oz = 92 where name = 'ps5 slim digital edition' and enabled;
update models set weight_oz = 22 where name = 'rog ally' and enabled;
update models set weight_oz = 24 where name = 'ROG Ally X' and enabled;
update models set weight_oz = 23 where name = 'Steam Deck OLED' and enabled;
update models set weight_oz = 30 where name = 'Switch' and enabled;
update models set weight_oz = 40 where name = 'Switch 2' and enabled;
update models set weight_oz = 10 where name = 'Switch Lite' and enabled;
update models set weight_oz = 32 where name = 'Switch OLED' and enabled;
update models set weight_oz = 103 where name = 'Xbox One S' and enabled;
update models set weight_oz = 69 where name = 'Xbox Series S' and enabled;
update models set weight_oz = 157 where name = 'Xbox Series X' and enabled;
update models set weight_oz = 8 where name = 'Fusion' and enabled;
update models set weight_oz = 6 where name = 'Hero 10' and enabled;
update models set weight_oz = 6 where name = 'Hero 11 Black' and enabled;
update models set weight_oz = 5 where name = 'Hero 11 Black Mini' and enabled;
update models set weight_oz = 6 where name = 'Hero 12 Black' and enabled;
update models set weight_oz = 6 where name = 'Hero 13 Black' and enabled;
update models set weight_oz = 6 where name = 'Hero 7 Black' and enabled;
update models set weight_oz = 6 where name = 'Hero 8 Black' and enabled;
update models set weight_oz = 6 where name = 'Hero 9 Black' and enabled;
update models set weight_oz = 6 where name = 'Max' and enabled;
update models set weight_oz = 14 where name = 'AirPods Max' and enabled;
update models set weight_oz = 4 where name = 'iPod Touch 7th Gen' and enabled;
update models set weight_oz = 3 where name = 'Series 10 GPS' and enabled;
update models set weight_oz = 3 where name = 'Series 10 GPS + Cellular' and enabled;
update models set weight_oz = 3 where name = 'Series 11 GPS' and enabled;
update models set weight_oz = 3 where name = 'Series 11 GPS + Cellular' and enabled;
update models set weight_oz = 3 where name = 'Series 5 GPS' and enabled;
update models set weight_oz = 3 where name = 'Series 5 GPS + Cellular' and enabled;
update models set weight_oz = 3 where name = 'Series 6 GPS' and enabled;
update models set weight_oz = 3 where name = 'Series 6 GPS + Cellular' and enabled;
update models set weight_oz = 3 where name = 'Series 7 GPS' and enabled;
update models set weight_oz = 3 where name = 'Series 7 GPS + Cellular' and enabled;
update models set weight_oz = 3 where name = 'Series 8 GPS' and enabled;
update models set weight_oz = 3 where name = 'Series 8 GPS + Cellular' and enabled;
update models set weight_oz = 3 where name = 'Series 9 GPS' and enabled;
update models set weight_oz = 3 where name = 'Series 9 GPS + Cellular' and enabled;
update models set weight_oz = 4 where name = 'Ultra' and enabled;
update models set weight_oz = 4 where name = 'Ultra 2' and enabled;
update models set weight_oz = 4 where name = 'Ultra 3' and enabled;
update models set weight_oz = 3 where name = 'Watch SE GPS' and enabled;
update models set weight_oz = 3 where name = 'Watch SE GPS + Cellular' and enabled;
update models set weight_oz = 3 where name = 'Watch SE GPS + Cellular 2nd Gen' and enabled;
update models set weight_oz = 3 where name = 'Watch SE GPS + Cellular 3rd Gen' and enabled;
update models set weight_oz = 3 where name = 'Watch SE GPS 2nd Gen' and enabled;
update models set weight_oz = 3 where name = 'Watch SE GPS 3rd Gen' and enabled;
update models set weight_oz = 18 where name = 'iPad 10.2 7th Gen (2019)' and enabled;
update models set weight_oz = 18 where name = 'iPad 10.2 8th Gen (2020)' and enabled;
update models set weight_oz = 18 where name = 'iPad 10.2 9th Gen (2021)' and enabled;
update models set weight_oz = 17 where name = 'iPad 10.9 10th Gen (2022)' and enabled;
update models set weight_oz = 17 where name = 'iPad 11 A16 11th Gen (2025)' and enabled;
update models set weight_oz = 17 where name = 'iPad 9.7 5th Gen (2017)' and enabled;
update models set weight_oz = 17 where name = 'iPad 9.7 6th Gen (2018)' and enabled;
update models set weight_oz = 17 where name = 'iPad Air 11 M2 (2024)' and enabled;
update models set weight_oz = 17 where name = 'iPad Air 11 M3 (2025)' and enabled;
update models set weight_oz = 17 where name = 'iPad Air 11 M4 (2026)' and enabled;
update models set weight_oz = 22 where name = 'iPad Air 13 M2 (2024)' and enabled;
update models set weight_oz = 22 where name = 'iPad Air 13 M3 (2025)' and enabled;
update models set weight_oz = 22 where name = 'iPad Air 13 M4 (2026)' and enabled;
update models set weight_oz = 17 where name = 'iPad Air 3rd Gen (2019)' and enabled;
update models set weight_oz = 17 where name = 'iPad Air 4th Gen (2020)' and enabled;
update models set weight_oz = 17 where name = 'iPad Air 5th Gen (2022)' and enabled;
update models set weight_oz = 12 where name = 'iPad Mini 3rd Gen (2014)' and enabled;
update models set weight_oz = 11 where name = 'iPad Mini 4th Gen (2015)' and enabled;
update models set weight_oz = 11 where name = 'iPad Mini 5th Gen (2019)' and enabled;
update models set weight_oz = 11 where name = 'iPad Mini 6th Gen (2021)' and enabled;
update models set weight_oz = 11 where name = 'iPad Mini 7th Gen (2024)' and enabled;
update models set weight_oz = 17 where name = 'iPad Pro 10.5 1st Gen (2017)' and enabled;
update models set weight_oz = 17 where name = 'iPad Pro 11 1st Gen (2018)' and enabled;
update models set weight_oz = 17 where name = 'iPad Pro 11 2nd Gen (2020)' and enabled;
update models set weight_oz = 17 where name = 'iPad Pro 11 3rd Gen (2021)' and enabled;
update models set weight_oz = 17 where name = 'iPad Pro 11 4th Gen (2022)' and enabled;
update models set weight_oz = 16 where name = 'iPad Pro 11 M4 Nano-texture Glass (2024)' and enabled;
update models set weight_oz = 16 where name = 'iPad Pro 11 M4 Standard Glass (2024)' and enabled;
update models set weight_oz = 16 where name = 'iPad Pro 11 M5 Nano-texture Glass (2025)' and enabled;
update models set weight_oz = 16 where name = 'iPad Pro 11 M5 Standard Glass (2025)' and enabled;
update models set weight_oz = 26 where name = 'iPad Pro 12.9 1st Gen (2015)' and enabled;
update models set weight_oz = 24 where name = 'iPad Pro 12.9 2nd Gen (2017)' and enabled;
update models set weight_oz = 23 where name = 'iPad Pro 12.9 3rd Gen (2018)' and enabled;
update models set weight_oz = 23 where name = 'iPad Pro 12.9 4th Gen (2020)' and enabled;
update models set weight_oz = 25 where name = 'iPad Pro 12.9 5th Gen (2021)' and enabled;
update models set weight_oz = 25 where name = 'iPad Pro 12.9 6th Gen (2022)' and enabled;
update models set weight_oz = 21 where name = 'iPad Pro 13 M4 Nano-texture Glass (2024)' and enabled;
update models set weight_oz = 21 where name = 'iPad Pro 13 M4 Standard Glass (2024)' and enabled;
update models set weight_oz = 21 where name = 'iPad Pro 13 M5 Nano-texture Glass (2025)' and enabled;
update models set weight_oz = 21 where name = 'iPad Pro 13 M5 Standard Glass (2025)' and enabled;
update models set weight_oz = 16 where name = 'iPad Pro 9.7 1st Gen (2016)' and enabled;
update models set weight_oz = 36 where name = 'vision pro' and enabled;
update models set weight_oz = 36 where name = 'vision pro m5' and enabled;
commit;
